//Cooper Griffin
//April 15th 2018
//Project Euler 2 Even Fibonnacci numbers
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

//Answer: 4613732

public class ProjectEuler2{
	public static void main(String[] args){
		run();
	}

	/*public static int fibonnaci(int n){
		if(n == 0){
			return 0;
		}
		else if(n ==1){
			return 1;
		}else{
			return fibonnaci(n-1) + fibonnaci(n-2);
		}
	}*/

	public static long fibonnaci(long limit){
		long x = 0;

		long y = 1;
		long z = 0;
		long sum = 0;

		while(x < limit){
			
			x = y + z;
			if(x % 2 == 0){
				sum += x;
				System.out.println(x);
			}
			z = y; 
			y = x;
		}

		return sum;
	}

	public static void run(){
		long sum = 0;
		//long result = 0;
		/*for(int i = 0; result < 4000000000L; i++){
			result = fibonnaci(i);
			if(result % 2 == 0){
				System.out.println(result);
				sum += result;
			}
		}*/
		sum = fibonnaci(4000000L);
		System.out.println("Sum = " + sum);
	}
}